## Random Sampling in Numpy

In [1]:
import numpy as np
import random

In [3]:
np.random.random(2)

array([0.82155471, 0.4299806 ])

In [4]:
np.random.random(1)

array([0.79926652])

In [5]:
#2d array random
np.random.random((3,3))

array([[0.32158746, 0.21282331, 0.94139459],
       [0.69849475, 0.82276722, 0.95701255],
       [0.07659079, 0.93122584, 0.03976178]])

In [7]:
np.random.randint(1,4)

1

In [12]:
np.random.randint(1,4,(4,4))

array([[2, 2, 2, 3],
       [2, 1, 3, 3],
       [3, 2, 1, 2],
       [2, 1, 3, 2]], dtype=int32)

In [13]:
np.random.randint(1,4,(2,4,4))

array([[[2, 3, 3, 1],
        [1, 3, 1, 2],
        [3, 1, 3, 1],
        [2, 3, 1, 2]],

       [[1, 3, 1, 1],
        [1, 2, 1, 1],
        [1, 3, 1, 3],
        [3, 1, 2, 1]]], dtype=int32)

In [11]:
#Same random output every run.
np.random.seed(10)
np.random.randint(1,4,(2,4,4))

array([[[2, 2, 1, 1],
        [2, 1, 2, 2],
        [1, 2, 2, 3],
        [1, 2, 1, 3]],

       [[1, 3, 1, 1],
        [1, 3, 1, 3],
        [3, 2, 1, 1],
        [3, 2, 3, 2]]], dtype=int32)

In [14]:
np.random.seed(10)
np.random.randint(1,4,(2,4,4))

array([[[2, 2, 1, 1],
        [2, 1, 2, 2],
        [1, 2, 2, 3],
        [1, 2, 1, 3]],

       [[1, 3, 1, 1],
        [1, 3, 1, 3],
        [3, 2, 1, 1],
        [3, 2, 3, 2]]], dtype=int32)

In [1]:
## random values types 4294967295
2**32 -1

4294967295

In [7]:
import numpy as np
np.random.rand(3)

array([0.18861691, 0.61032565, 0.51953491])

In [10]:
np.random.rand(3,3)

array([[0.67090838, 0.28275785, 0.40158954],
       [0.34914927, 0.98027134, 0.97499835],
       [0.92100566, 0.91437576, 0.76491153]])

In [11]:
np.random.randn(3,3)

array([[ 1.04495359,  0.97377062,  0.5854063 ],
       [-0.67633192, -0.45625807, -1.12883907],
       [-0.37500714,  1.22624923, -1.91189532]])

In [15]:
## any random choice in list
               x =[1,2,3,4]
int(           np.random.choice(x)                             )

4

In [17]:
int(     np.random.choice(x)        )

1

In [20]:
int(     np.random.choice(x)        )

3

In [21]:
for i in range(20):
    print(np.random.choice(x))

4
2
4
1
2
2
2
1
2
3
4
3
1
1
2
4
4
1
4
4


In [22]:
x

[1, 2, 3, 4]

In [23]:
np.random.permutation(x)

array([4, 3, 2, 1])

In [26]:
np.random.permutation(x)

array([3, 4, 2, 1])