## Numpy Mathematical Operation


In [2]:
import numpy as np

In [4]:
arr1 = np.arange(1,10).reshape(3,3)
arr2 = np.arange(1,10).reshape(3,3)
print(arr1,arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]] [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
#import numpy as np
arr1 = np.arange(1,10).reshape(3,3)
arr2 = np.arange(1,10).reshape(3,3)
print(arr1)
print(arr2)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Addition

In [9]:
arr1 + arr2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [10]:
np.add(arr1,arr2)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

## Subtraction

In [11]:
arr1-arr2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [14]:
np.subtract(arr1,arr2)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [15]:
arr1-arr2-arr1

array([[-1, -2, -3],
       [-4, -5, -6],
       [-7, -8, -9]])

## Division

In [16]:
arr1/arr2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
np.divide(arr1,arr2)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## Multiplication

In [18]:
arr2*arr1

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [20]:
np.multiply(arr1,arr2)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

## Matrix product

In [25]:
# first row with first coloumn
arr1.dot(arr2)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [22]:
arr1 @ arr2

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [26]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Max Function

In [33]:
int(arr1.max())

9

In [32]:

int(arr1.argmax())


8

In [34]:
arr1.max(axis = 0)

array([7, 8, 9])

In [35]:
arr1.max(axis = 1)

array([3, 6, 9])

## Min Function

In [38]:
arr1.min()

np.int64(1)

In [40]:
int(arr1.min())

1

In [50]:
int(arr1.argmin())

0

In [42]:
arr1.min(axis = 0)

array([1, 2, 3])

## Sum function

In [69]:
np.sum(arr1)

np.int64(45)

In [70]:
np.sum(arr1,axis = 1)

array([ 6, 15, 24])

## Mean Function

In [59]:
np.mean(arr1)



np.float64(5.0)

## SQuare Root

In [60]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [61]:
np.sqrt(4)

np.float64(2.0)

In [62]:
np.sqrt(121)

np.float64(11.0)

 ## Standard Devision

In [64]:
#np.std(arr1)
int(np.std(arr1))


2

## Exponent

In [65]:
np.exp(arr1)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [66]:
np.exp(333)

np.float64(4.169293549452358e+144)

## Log

In [67]:
np.log(arr1)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [68]:
np.log(30)

np.float64(3.4011973816621555)