In [ ]:
import numpy as np

In [7]:
arr_1d = np.array([1,2,3,4])
print(arr_1d)

[1 2 3 4]


In [8]:
type(arr_1d)

numpy.ndarray

In [9]:
arr_1d.ndim

1

In [10]:
arr_2d = np.array([[1,3,5,7],[2,4,6,8]]) 
print(arr_2d)

[[1 3 5 7]
 [2 4 6 8]]


In [11]:
arr_2d.ndim

2

In [13]:
arr_1d.size

4

In [14]:
arr_2d.size

8

In [15]:
arr_2d.shape

(2, 4)

In [16]:
arr_2d.dtype

dtype('int64')