## Numpy Function :

In [1]:
import numpy as np

## arange()

In [4]:
#np.arange(star,end,steps)
arr_1d=np.arange(1,13)
print(arr_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [9]:
even_arr = np.arange(2, 15,2)
print(even_arr)


[ 2  4  6  8 10 12 14]


## linspace()

In [12]:
np.linspace(1,6,4)

array([1.        , 2.66666667, 4.33333333, 6.        ])

In [18]:
np.linspace(1,158,15)

array([  1.        ,  12.21428571,  23.42857143,  34.64285714,
        45.85714286,  57.07142857,  68.28571429,  79.5       ,
        90.71428571, 101.92857143, 113.14285714, 124.35714286,
       135.57142857, 146.78571429, 158.        ])

## reshape()

In [24]:
# converting 1d array into 2d 
arr_2d = arr_1d.reshape(3, 4)
print(arr_2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [29]:
# converting 1d array into 3d
arr_3d = arr_1d.reshape(2, 3, 2)
print(arr_3d)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [39]:
#import numpy as np
arr = np.arange(1,13).reshape(2,6)
print(arr)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


## ravel()


In [40]:
# ravel is use to convert 2d arr into 1d
ar.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

## flatten()

In [41]:
# same as ravel 
arr.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

## transpose()

In [45]:
#converting row into columns
arr.transpose()

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])

In [47]:
# T-transpose()
arr.T

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])